# Generated by Django 4.0.1 on 2022-03-01 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loadimage', '0005_alter_tablaarchivo_url_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_img', models.CharField(max_length=50)),
                ('url_img', models.CharField(max_length=50)),
                ('format_img', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img/')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'TableImages',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='TablaArchivo',
        ),
    ]
